qubell/contrib-python-qubell-client

qubell/api/private/testing/__init__.py

http://nedbatchelder.com/blog/200711/rethrowing_exceptions_in_python.html

Properly raise exception in tearDown

---

qubell/api/private/instance.py

Needed for docker self-check tests.

Added some new status checks to instance

---

qubell/api/provider/__init__.py
qubell/api/provider/router.py
qubell/tests/provider/test_route_decorators.py
qubell/tests/provider/test_router.py

Reverts qubell/contrib-python-qubell-client#127

Revert "Use same session for requests"

---

qubell/api/private/instance.py

Support of API changes made in https://github.com/qubell/vermilion/pull/5079
Impact:
- instance-related tests

Instance API improved to support both old and new instance panel

---

qubell/api/private/instance.py
qubell/api/private/organization.py
qubell/api/private/testing/__init__.py
qubell/api/tools/__init__.py

Fixes unrelated error message (AttributeError: 'bool' object has no attribute 'strip') when instance has not converged in timeout

Better errors in testing

---

qubell/api/private/organization.py
qubell/api/provider/router.py

[WIP] API components screen

---

qubell/api/private/service.py
qubell/api/provider/router.py

Reopened https://github.com/qubell/contrib-python-qubell-client/pull/156

Reopened "Wait for config propagation when adding shared service to catalog"

---

integration_tests/__init__.py
qubell/api/private/environment.py
qubell/api/testing/__init__.py

Also show logs for components testing.

Another workaround for service addition issue

---

qubell/api/private/application.py

clean app before removing

---

README
qubell/api/private/application.py
qubell/api/provider/router.py
qubell/cli/__main__.py
qubell/cli/yamlutils.py
requirements.txt

commands
```
$ python -mqubell.cli 
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
Options:
--tenant TEXT        Tenant url to use, QUBELL_TENANT by default
--user TEXT          User to use, QUBELL_USER by default
--password TEXT      Password to use, QUBELL_PASSWORD by default
--organization TEXT  Organization to use, QUBELL_ORGANIZATION by default
--help               Show this message and exit.
Commands:
create_org
export_app
import_app
list_apps
```
app export
```
$ python -mqubell.cli export_app --help
Usage: __main__.py export_app [OPTIONS] APPLICATION
Options:
--recursive / --non-recursive  Export also dependencies.
--output-dir TEXT              Output directory for manifest files, current
by default.
--help                         Show this message and exit.
```
app import
```
$ …
```

Initial version of cli

---

qubell/api/provider/__init__.py
qubell/api/provider/router.py
qubell/tests/provider/test_route_decorators.py

* Added support for bypassing `json` argument to requests session
* Fixed content type configuration for public API methods

Improved support for public API

---

qubell/api/private/revision.py
qubell/api/provider/router.py

Reverts qubell/contrib-python-qubell-client#183
wrong force parameter type

Revert "split delete_revision and delete_revision_with_check up"

---

qubell/api/private/revision.py
qubell/api/provider/router.py

api extension for delete revision call

force remove paramter for delete_revision

---

qubell/api/provider/router.py

Runtime component routes, minor refacroting

---

README
qubell/api/private/application.py
qubell/api/provider/router.py
qubell/cli/__main__.py
qubell/cli/yamlutils.py
requirements.txt

This is cherry-pick of commits merged to master instead of develop.

Cli utilities initials

---

qubell/api/private/application.py
qubell/api/private/environment.py
qubell/api/private/platform.py
qubell/api/provider/router.py
qubell/cli/__main__.py
requirements.txt
setup.py

Cherry-picked chemikadze commits, updated cli.
Usage:
```
$ nomi app list
5697b4bee4b0138b51d10b92 Secure Vault 2.0
5697b4bee4b0138b51d10b94 Resource Pool
5697b4bee4b0138b51d10b98 Workflow Service
5697b4bee4b0138b51d10b9a Cloud Account
569e4a0ce4b01bc5448397de Red SortingTests
569e4a0be4b01bc5448397db Gray SortingTests
```                
``` 
$nomi app export 569e4a0be4b01bc5448397db "Red SortingTests"
Saving 569e4a0be4b01bc5448397db v1 => Gray SortingTests-v1.yml OK
Saving Red SortingTests v1 => Red SortingTests-v1.yml OK
``` 
``` 
$ nomi appli import ./Green\ SortingTests-v1.yml ./Green\ SortingTests-v2.yml -w
(u'./Green SortingTests-v1.yml', u'./Green SortingTests-v2.yml')
Importing ./Green SortingTests-v1.yml => Green SortingTests 569e4a09e4b01bc5448397d8 OK
Importing ./Green …
```

Cli utilities update

---

qubell/api/private/application.py
qubell/cli/__main__.py

Fix get_manifest

---

qubell/api/private/service.py

Add support for amazon account

---

qubell/api/provider/router.py

Ref: qubell/vermilion#7020, qubell/vermilion#7060, qubell/vermilion#7140.

RBAC public API routes

---

integration_tests/test_environment.py
qubell/api/private/environment.py
qubell/api/provider/router.py

Native support clone environment

---

qubell/api/private/instance.py
qubell/api/tools/__init__.py
qubell/cli/__main__.py

fixes #227, #241, #242, #243, #244 
Added --nocolorize option to output raw text
Added instance describe <id> --json to output raw json

CLI: Fix bugs, improvements

---

qubell/api/private/service.py

Added support for GCE

---

qubell/api/private/manifest.py

When Manifest class is used the content is not loaded immediately. But only when content is requested.
This should speed up usage of Manifest in global context.

Lazy manifest content loader, avoid constructor time loading

---

qubell/api/globals.py
qubell/api/private/platform.py
qubell/api/provider/__init__.py
qubell/api/provider/jwtauth.py
qubell/api/provider/router.py
qubell/cli/__main__.py
qubell/tests/provider/test_route_decorators.py

New ``nomi`` commands and and authentication options:
1. To generate a new session token from a refresh token:
```
nomi token generate [--verbose] <YOUR_REFRESH_TOKEN>
```
2. To authenticate with the session token use the ``--token`` option:
```
nomi --token <YOUR_SESSION_TOKEN> organization list
```
OR alternatively set the ``QUBELL_TOKEN`` environment variable:
```
export set QUBELL_TOKEN=<YOUR_SESSION_TOKEN>
nomi organization list
```

Support for JWT based authentication

---

qubell/api/private/instance.py
qubell/api/provider/router.py

[for jenkins] Separate wfhistory download

---

qubell/api/private/instance.py
qubell/api/provider/router.py

Now Instance.details doesn't have workflowHistory, we can download it from router.get_instance_workflowhistory
duplicate #269

Separate wfhistory download

---

qubell/api/private/instance.py
qubell/api/provider/router.py

[for jenkins]Separate wfhistory download again

---

qubell/api/private/instance.py
qubell/api/provider/router.py

Now Instance.details have workflowsInfo but doesn't have workflowHistory (previous version doesn't have workflowsInfo)

Separate wfhistory download again
